services:
    emotion_service:
      build: 
       context : ./emotion_service
       dockerfile: Dockerfile
      ports:
        - "5000:5000"

      networks:
        - "mynetwork"

      volumes:
        - "C:/ml/nutricio/backend/d3/Emotion_final.csv:/d3/Emotion_final.csv"
    recomendation_service:
      build: 
       context:  ./recommendation_service
       dockerfile: Dockerfile
      ports:
        - "5001:5001"
      env_file:
        - "./recommendation_service/.env"
      networks:
        - "mynetwork"



networks:
  mynetwork:
    driver : bridge